---

apiVersion: v1
kind: Secret
data:
  connections.yaml: {{ connections }}
metadata:
  name: halfpipe-connections
type: Opaque

---

apiVersion: v1
kind: Secret
data:
  AWS_ACCESS_KEY_ID: {{ b64_aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ b64_aws_secret_access_key }}
metadata:
  name: aws-access-keys
