apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: hp-server
  labels:
    app: hp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hp-server
  template:
    metadata:
      labels:
        app: hp-server
    spec:
      containers:
      - command:
        - hp
        - serve
        image: halfpipe:8
        imagePullPolicy: IfNotPresent
        name: hp-server
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /home/dataops/.halfpipe
          name: connections
      volumes:
      - name: connections
        secret:
          secretName: halfpipe-connections

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: hp-server
  name: hp-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hp-server
  type: NodePort
